[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "cd bus_tracking/backend && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_superuser_if_none && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
